apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-configmap
data:
  init.sql: |
    DROP USER IF EXISTS 'admin'@'%';
    CREATE USER 'admin'@'%' IDENTIFIED BY 'admin@123';
    GRANT ALL PRIVILEGES ON pyapplicationdb.* TO 'admin'@'%';
    FLUSH PRIVILEGES;

    CREATE DATABASE IF NOT EXISTS pyapplicationdb;
    USE pyapplicationdb;
    CREATE TABLE IF NOT EXISTS random_words (
        id INT AUTO_INCREMENT PRIMARY KEY,
        word VARCHAR(255) NOT NULL
    );
    INSERT INTO random_words (word) VALUES ('example');
